AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  GenericSendGridEventHandler

  A stub for a Lambda subscribed to SNS topic and processes messages (sendgrid events) as required by your business.

Resources:

  ##########################################################################
  #  Policy
  #                          
  #  Provide permission for SNS to invoke the Lambda function
  ########################################################################## 
  #SendGridGenericHandlerFunctionPermission:
  #  Type: 'AWS::Lambda::Permission'
  #  Properties:
  #    Action: 'lambda:InvokeFunction'
  #    FunctionName: !Ref SendGridGenericHandlerFunction
  #    Principal: sns.amazonaws.com

  ##########################################################################
  #  (SendGridGenericHandlerFunction) Lambda Function                            
  #                          
  #  This function receives messages messages from SNS and inspects them  
  #  for additional processing. This is a "stub" function ready for you
  # to add your additional functionality!
  ##########################################################################
  SendGridGenericHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:      
      Description: Lambda invoked by SNS topic to process Inbound Emails
      CodeUri: lambdas/generic-handler/
      Handler: app.lambdaHandler
      AutoPublishAlias: live
      Runtime: nodejs20.x
      Architectures:
        - arm64
      Timeout: 3
      MemorySize: 128
      Environment:
        Variables:
          REGION: !Ref "AWS::Region"
      Events:
        SNSEvent:
          Type: SNS
          Properties:            
            Topic: !ImportValue 'SGInboundEmailTopicARN'
    